BD_Constituencies = [
            "Bagerhat-1", "Bagerhat-2", "Bagerhat-3", "Bagerhat-4",
            "Bandarban-1",
            "Barguna-1", "Barguna-2",
            "Barisal-1", "Barisal-2", "Barisal-3", "Barisal-4", "Barisal-5", "Barisal-6",
            "Bhola-1", "Bhola-2", "Bhola-3", "Bhola-4",
            "Bogura-1", "Bogura-2", "Bogura-3", "Bogura-4", "Bogura-5", "Bogura-6", "Bogura-7",
            "Brahmanbaria-1", "Brahmanbaria-2", "Brahmanbaria-3", "Brahmanbaria-4", "Brahmanbaria-5", "Brahmanbaria-6",
            "Chandpur-1", "Chandpur-2", "Chandpur-3", "Chandpur-4",
            "Chattogram-1", "Chattogram-2", "Chattogram-3", "Chattogram-4", "Chattogram-5", "Chattogram-6",
            "Chattogram-7", "Chattogram-8", "Chattogram-9", "Chattogram-10", "Chattogram-11", "Chattogram-12",
            "Chattogram-13", "Chattogram-14", "Chattogram-15",
            "Chuadanga-1", "Chuadanga-2",
            "Comilla-1", "Comilla-2", "Comilla-3", "Comilla-4", "Comilla-5", "Comilla-6", "Comilla-7", "Comilla-8",
            "Comilla-9", "Comilla-10",
            "Cox's Bazar-1", "Cox's Bazar-2", "Cox's Bazar-3",
            "Dhaka-1", "Dhaka-2", "Dhaka-3", "Dhaka-4", "Dhaka-5", "Dhaka-6", "Dhaka-7", "Dhaka-8", "Dhaka-9",
            "Dhaka-10", "Dhaka-11", "Dhaka-12", "Dhaka-13", "Dhaka-14", "Dhaka-15", "Dhaka-16", "Dhaka-17", "Dhaka-18",
            "Dinajpur-1", "Dinajpur-2", "Dinajpur-3", "Dinajpur-4", "Dinajpur-5",
            "Faridpur-1", "Faridpur-2", "Faridpur-3", "Faridpur-4",
            "Feni-1", "Feni-2", "Feni-3", "Feni-4",
            "Gaibandha-1", "Gaibandha-2", "Gaibandha-3", "Gaibandha-4",
            "Gazipur-1", "Gazipur-2", "Gazipur-3", "Gazipur-4", "Gazipur-5",
            "Gopalganj-1", "Gopalganj-2", "Gopalganj-3",
            "Habiganj-1", "Habiganj-2", "Habiganj-3",
            "Jamalpur-1", "Jamalpur-2",
            "Jashore-1", "Jashore-2", "Jashore-3", "Jashore-4",
            "Jhenaidah-1", "Jhenaidah-2", "Jhenaidah-3",
            "Joypurhat-1", "Joypurhat-2",
            "Junaydah-1", "Junaydah-2", "Junaydah-3", "Junaydah-4", "Junaydah-5", "Junaydah-6",
            "Kishoreganj-1", "Kishoreganj-2", "Kishoreganj-3", "Kishoreganj-4",
            "Khulna-1", "Khulna-2", "Khulna-3", "Khulna-4", "Khulna-5",
            "Kurigram-1", "Kurigram-2", "Kurigram-3", "Kurigram-4", "Kurigram-5", "Kurigram-6",
            "Kushtia-1", "Kushtia-2", "Kushtia-3",
            "Lakshmipur-1", "Lakshmipur-2", "Lakshmipur-3",
            "Lalmonirhat-1", "Lalmonirhat-2", "Lalmonirhat-3",
            "Madaripur-1", "Madaripur-2",
            "Magura-1", "Magura-2",
            "Manikganj-1", "Manikganj-2", "Manikganj-3",
            "Meherpur-1", "Meherpur-2",
            "Moulvibazar-1", "Moulvibazar-2", "Moulvibazar-3",
            "Munshiganj-1", "Munshiganj-2",
            "Mymensingh-1", "Mymensingh-2", "Mymensingh-3",
            "Naogaon-1", "Naogaon-2", "Naogaon-3", "Naogaon-4", "Naogaon-5",
            "Narail-1", "Narail-2",
            "Narayanganj-1", "Narayanganj-2", "Narayanganj-3", "Narayanganj-4", "Narayanganj-5",
            "Narsingdi-1", "Narsingdi-2", "Narsingdi-3",
            "Natore-1", "Natore-2", "Natore-3",
            "Netrokona-1", "Netrokona-2", "Netrokona-3",
            "Nilphamari-1", "Nilphamari-2", "Nilphamari-3", "Nilphamari-4",
            "Noakhali-1", "Noakhali-2", "Noakhali-3", "Noakhali-4",
            "Pabna-1", "Pabna-2", "Pabna-3", "Pabna-4",
            "Panchagarh-1", "Panchagarh-2",
            "Patuakhali-1", "Patuakhali-2", "Patuakhali-3", "Patuakhali-4",
            "Pirojpur-1", "Pirojpur-2",
            "Rajbari-1", "Rajbari-2",
            "Rajshahi-1", "Rajshahi-2", "Rajshahi-3", "Rajshahi-4", "Rajshahi-5",
            "Rangamati-1",
            "Rangpur-1", "Rangpur-2", "Rangpur-3", "Rangpur-4",
            "Satkhira-1", "Satkhira-2", "Satkhira-3", "Satkhira-4",
            "Shariatpur-1", "Shariatpur-2", "Shariatpur-3",
            "Sherpur-1", "Sherpur-2",
            "Sirajganj-1", "Sirajganj-2", "Sirajganj-3",
            "Sunamganj-1", "Sunamganj-2", "Sunamganj-3",
            "Sylhet-1", "Sylhet-2", "Sylhet-3",
            "Tangail-1", "Tangail-2", "Tangail-3", "Tangail-4",
            "Thakurgaon-1", "Thakurgaon-2"
        ]