# Form implementation generated from reading ui file 'software/CandidateCard.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(625, 257)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.backCard1_2 = QtWidgets.QWidget(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.backCard1_2.sizePolicy().hasHeightForWidth())
        self.backCard1_2.setSizePolicy(sizePolicy)
        self.backCard1_2.setMinimumSize(QtCore.QSize(0, 194))
        self.backCard1_2.setMaximumSize(QtCore.QSize(16777215, 194))
        self.backCard1_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"border: 1px solid rgb(252, 251, 253);")
        self.backCard1_2.setObjectName("backCard1_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.backCard1_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.backcard_4 = QtWidgets.QWidget(parent=self.backCard1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.backcard_4.sizePolicy().hasHeightForWidth())
        self.backcard_4.setSizePolicy(sizePolicy)
        self.backcard_4.setMinimumSize(QtCore.QSize(101, 101))
        self.backcard_4.setMaximumSize(QtCore.QSize(101, 101))
        self.backcard_4.setStyleSheet("background-color: rgb(43, 91, 193);\n"
"border-radius: 20px;\n"
"border: 1px solid rgb(200, 210, 240);\n"
"")
        self.backcard_4.setObjectName("backcard_4")
        self.horizontalLayout_7.addWidget(self.backcard_4)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.name3 = QtWidgets.QLabel(parent=self.backCard1_2)
        font = QtGui.QFont()
        font.setFamily("13")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.name3.setFont(font)
        self.name3.setStyleSheet("color: #0f1724; /* dark slate */\n"
"\n"
"font: 20px bold;")
        self.name3.setObjectName("name3")
        self.verticalLayout_7.addWidget(self.name3)
        self.constituency3 = QtWidgets.QLabel(parent=self.backCard1_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.constituency3.setFont(font)
        self.constituency3.setStyleSheet("color: #0f1724; /* dark slate */\n"
"\n"
"font: 18px;")
        self.constituency3.setObjectName("constituency3")
        self.verticalLayout_7.addWidget(self.constituency3)
        self.party3 = QtWidgets.QLabel(parent=self.backCard1_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        self.party3.setFont(font)
        self.party3.setStyleSheet("color: #0f1724; /* dark slate */\n"
"\n"
"font: 18px;")
        self.party3.setObjectName("party3")
        self.verticalLayout_7.addWidget(self.party3)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(0, -1, 0, 6)
        self.horizontalLayout_6.setSpacing(4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.edit3 = QtWidgets.QPushButton(parent=self.backCard1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit3.sizePolicy().hasHeightForWidth())
        self.edit3.setSizePolicy(sizePolicy)
        self.edit3.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        self.edit3.setFont(font)
        self.edit3.setStyleSheet("QPushButton {\n"
"border-radius: 10px;\n"
"  background:rgb(38, 83, 181);\n"
"color: White;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   background: rgb(34, 72, 145);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(23, 48, 96)\n"
"}\n"
"")
        self.edit3.setObjectName("edit3")
        self.horizontalLayout_6.addWidget(self.edit3)
        self.delete3 = QtWidgets.QPushButton(parent=self.backCard1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete3.sizePolicy().hasHeightForWidth())
        self.delete3.setSizePolicy(sizePolicy)
        self.delete3.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        self.delete3.setFont(font)
        self.delete3.setStyleSheet("QPushButton {\n"
"border-radius: 10px;\n"
"  background: rgb(255, 51, 64);\n"
"color: White;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   background: rgb(238, 54, 69);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background:rgb(192, 44, 55)\n"
"}\n"
"")
        self.delete3.setObjectName("delete3")
        self.horizontalLayout_6.addWidget(self.delete3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.gridLayout.addWidget(self.backCard1_2, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.name3.setText(_translate("Form", "Sazid Ahmed Ekram"))
        self.constituency3.setText(_translate("Form", "Dhaka-12"))
        self.party3.setText(_translate("Form", "BNP"))
        self.edit3.setText(_translate("Form", "Edit"))
        self.delete3.setText(_translate("Form", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
